name: traductor_simultaneo
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_isolate: ^2.0.0
  speech_to_text: ^7.0.0
  translator: ^1.0.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  shared_preferences: ^2.0.13
  provider: ^6.0.0
  convex_bottom_bar: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
